### ISSUE TITLE
Unable To Run this On Ubuntu

### ISSUE THREAD

**Issue by Swapnil511994** [keethesh/UdemyCourseGrabber#2]
root@cuphandtechnology:/home/admin/web/swapnilvishwakarma.com/public_html/pythonscript/UdemyCourseGrabber# python3 main.py
Geckodriver not detected, it will now be downloaded...

Looking for [geckodriver v0.26.0 linux64] driver in cache
File found in cache by path [/root/.wdm/drivers/geckodriver/v0.26.0/linux64/geckodriver]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/web/swapnilvishwakarma.com/public_html/pythonscript/UdemyCourseGrabber/functions.py", line 291, in <module>
    browser = Firefox(options=opts)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from functions import *
  File "/home/admin/web/swapnilvishwakarma.com/public_html/pythonscript/UdemyCourseGrabber/functions.py", line 294, in <module>
    browser = Firefox(executable_path=GeckoDriverManager().install(), options=opts)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

root@cuphandtechnology:/home/admin/web/swapnilvishwakarma.com/public_html/pythonscript/UdemyCourseGrabber#

**Comment by keethesh** [comment]
Is it working if you copy Geckodriver to the project's directory?

**Comment by keethesh** [comment]
I just updated the files, it should be working now. Please try and confirm that it is working.

**Comment by Swapnil511994** [comment]
**I'm not a python developer**
root@cuphandtechnology:/home/admin/web/swapnilvishwakarma.com/public_html/UdemyCourseGrabber# python3 main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from functions import *
  File "/home/admin/web/swapnilvishwakarma.com/public_html/UdemyCourseGrabber/functions.py", line 6, in <module>
    from webdrivermanager import GeckoDriverManager
ModuleNotFoundError: No module named 'webdrivermanager'


root@cuphandtechnology:/home/admin/web/swapnilvishwakarma.com/public_html/UdemyCourseGrabber# python main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from functions import *
  File "/home/admin/web/swapnilvishwakarma.com/public_html/UdemyCourseGrabber/functions.py", line 127
SyntaxError: Non-ASCII character '\xe2' in file /home/admin/web/swapnilvishwakarma.com/public_html/UdemyCourseGrabber/functions.py on line 127, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
root@cuphandtechnology:/home/admin/web/swapnilvishwakarma.com/public_html/UdemyCourseGrabber#

**Comment by keethesh** [comment]
- I added a new module, so you should do pip install -r requirements. txt again

**Comment by Swapnil511994** [comment]
**I'm running this on digital ocean server, will try it on machine and let you know how it goes :)**

root@cuphandtechnology:/home/admin/web/swapnilvishwakarma.com/public_html/UdemyCourseGrabber# python3 main.py
Geckodriver not detected, it will now be downloaded...
Traceback (most recent call last):
  File "/home/admin/web/swapnilvishwakarma.com/public_html/UdemyCourseGrabber/functions.py", line 294, in <module>
    browser = Firefox(options=opts)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from functions import *
  File "/home/admin/web/swapnilvishwakarma.com/public_html/UdemyCourseGrabber/functions.py", line 298, in <module>
    gdd.download_and_install()
  File "/usr/local/lib/python3.6/dist-packages/webdrivermanager/webdrivermanager.py", line 279, in download_and_install
    tar.extractall(extract_dir)
  File "/usr/lib/python3.6/tarfile.py", line 2010, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.6/tarfile.py", line 2052, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.6/tarfile.py", line 2122, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.6/tarfile.py", line 2163, in makefile
    with bltn_open(targetpath, "wb") as target:
OSError: [Errno 26] Text file busy: '/usr/local/share/WebDriverManager/gecko/v0.26.0/geckodriver-v0.26.0-linux64/geckodriver'
root@cuphandtechnology:/home/admin/web/swapnilvishwakarma.com/public_html/UdemyCourseGrabber#

**Comment by keethesh** [comment]
Are you running it via ssh?

**Comment by Swapnil511994** [comment]
Yes, I'm running it via ssh

**Comment by CyriacBr** [comment]
You need to install geckodriver and put in the path. Basically download it and move the file to /usr/local/bin.

https://stackoverflow.com/questions/40208051/selenium-using-python-geckodriver-executable-needs-to-be-in-path

**Comment by keethesh** [comment]
Is the problem still occurring? @Swapnil511994

**Comment by Swapnil511994** [comment]
I'll surely update you soon

**Comment by keethesh** [comment]
Still waiting for an update...
