### ISSUE TITLE
Browsing context has been discarded

### ISSUE THREAD

**Issue by XOKP** [keethesh/UdemyCourseGrabber#4]
I tried to run it and received:
_selenium.common.exceptions.NoSuchWindowException: Message: Browsing context has been discarded_

```
~/UdemyCourseGrabber# python3 main.py
Paste in your Udemy course URL: https://www.udemy.com/course/modern-javascript-from-novice-to-ninja/
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    course_info = get_info(udemy_url)
  File "/root/UdemyCourseGrabber/functions.py", line 248, in get_info
    course_name = get_course_name(udemy_url)
  File "/root/UdemyCourseGrabber/functions.py", line 15, in get_course_name
    browser.find_element_by_css_selector(".btn-primary > span:nth-child(1)")
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: Browsing context has been discarded
```

Great work, please keep it up. Thank you.

**Comment by keethesh** [comment]
What firefox version are you using? Also, thank you for your kind words, it motivates me.

**Comment by keethesh** [comment]
Is the problem still occurring?

**Comment by XOKP** [comment]
Sorry for the late response. I installed a fresh Debian 10 to try again just now.

My Firefox version is firefox-esr (68.3.0esr-1~deb10u1).

I got a different error this times. 🤔

_Failed to convert data to an object_

```
~/UdemyCourseGrabber# python3 main.py
Geckodriver not detected, it will now be downloaded...
2335kb [00:01, 1245.72kb/s]
Paste in your Udemy course URL: https://www.udemy.com/course/modern-javascript-from-novice-to-ninja/

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    course_name = get_course_name(udemy_url)
  File "/root/UdemyCourseGrabber/functions.py", line 30, in get_course_name
    "//h1[contains(@class,'clp-lead__title')]").text
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to convert data to an object
```

**Comment by keethesh** [comment]
Can you try changing the line
`browser.find_element_by_css_selector(".btn-primary > span:nth-child(1)")` in functions.py (line 28) by `browser.find_element_by_xpath("//span[contains(text(),'Add to cart')]")` and telling me the output?

**Comment by XOKP** [comment]
It is better this times, it started the searching before it failed at 3/11 with an error message:

_selenium.common.exceptions.NoSuchWindowException: Message: Browsing context has been discarded_

```
# python3 main.py
Geckodriver not detected, it will now be downloaded...
2335kb [00:02, 1075.24kb/s]

Paste in your Udemy course URL, or the course name: https://www.udemy.com/course/modern-javascript-from-novice-to-ninja/

Searching for course on freecourseudemy.com:  27%|█████████████▎                                   | 3/11 [00:21<01:01,  7.73s/it]Traceback (most recent call last):
  File "main.py", line 27, in <module>
    course_info = get_sites(course_name)
  File "/root/UdemyCourseGrabber/functions.py", line 54, in get_sites
    site.get("search_element") + str(course_name) + "')]")
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: Browsing context has been discarded

Searching for course on freecourseudemy.com:  27%|█████████████▎                                   | 3/11 [00:24<01:04,  8.03s/it]
```

**Comment by keethesh** [comment]
Sorry for the late response! I don't actually know why this is happening, but I'll rewrite the program (once again) so that it uses Scrapy. It should be working then.
