### ISSUE TITLE
Error involving Geckodriver?

### ISSUE THREAD

**Issue by RHQ-Rusty** [keethesh/UdemyCourseGrabber#8]
```
PS X:\UdemyCourseGrabber-master\UdemyCourseGrabber-master> py main.py
Geckodriver not detected, it will now be downloaded...
Traceback (most recent call last):
  File "C:\Users\UNAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\UNAME\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\UNAME\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X:\UdemyCourseGrabber-master\UdemyCourseGrabber-master\functions.py", line 20, in start_browser
    driver = Firefox(firefox_profile=firefox_profile, options=opts)
  File "C:\Users\UNAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\UNAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UNAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\UNAME\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\UNAME\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from functions import *
  File "X:\UdemyCourseGrabber-master\UdemyCourseGrabber-master\functions.py", line 167, in <module>
    browser = start_browser()
  File "X:\UdemyCourseGrabber-master\UdemyCourseGrabber-master\functions.py", line 25, in start_browser
    driver = Firefox(firefox_profile=firefox_profile, options=opts)
  File "C:\Users\UNAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\UNAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

Returning this error upon every execution of main.py. Where can one obtain the geckodriver?

**Comment by keethesh** [comment]
Download Geckodriver from [here](https://github.com/mozilla/geckodriver/releases), then put it in the same folder as the program.

**Comment by keethesh** [comment]
I made some changes so things like that won't happen again. Will commit in some time.
